
services:
  zoo1:
    image: openjdk
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        read_only: false
        source: ./azbin
        target: /zoo/azbin
      - type: bind
        read_only: true
        source: ./scripts
        target: /zoo/scripts
      - type: bind
        read_only: false
        source: ./conf
        target: /zoo/conf
      - type: bind
        read_only: false
        source: ./dataDirs
        target: /zoo/dataDirs
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /zoo/server.jar
    
    networks:
      zookeeper-network:
        ipv4_address: 172.200.202.2

    entrypoint: /zoo/scripts/runServer.sh --config /zoo/conf/1 start-foreground

  zoo2:
    image: openjdk
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        read_only: false
        source: ./azbin
        target: /zoo/azbin
      - type: bind
        read_only: true
        source: ./scripts
        target: /zoo/scripts
      - type: bind
        read_only: false
        source: ./conf
        target: /zoo/conf
      - type: bind
        read_only: false
        source: ./dataDirs
        target: /zoo/dataDirs
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /zoo/server.jar

    networks:
      zookeeper-network:
        ipv4_address: 172.200.202.3

    entrypoint: /zoo/scripts/runServer.sh --config /zoo/conf/2 start-foreground

  zoo3:
    image: openjdk
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        read_only: false
        source: ./azbin
        target: /zoo/azbin
      - type: bind
        read_only: true
        source: ./scripts
        target: /zoo/scripts
      - type: bind
        read_only: false
        source: ./conf
        target: /zoo/conf
      - type: bind
        read_only: false
        source: ./dataDirs
        target: /zoo/dataDirs
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /zoo/server.jar

    networks:
      zookeeper-network:
        ipv4_address: 172.200.202.4

    entrypoint: /zoo/scripts/runServer.sh --config /zoo/conf/3 start-foreground

  zoo4:
    image: openjdk
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        read_only: false
        source: ./azbin
        target: /zoo/azbin
      - type: bind
        read_only: true
        source: ./scripts
        target: /zoo/scripts
      - type: bind
        read_only: false
        source: ./conf
        target: /zoo/conf
      - type: bind
        read_only: false
        source: ./dataDirs
        target: /zoo/dataDirs
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /zoo/server.jar

    networks:
      zookeeper-network:
        ipv4_address: 172.200.202.5

    entrypoint: /zoo/scripts/runServer.sh --config /zoo/conf/4 start-foreground

  zoo5:
    image: openjdk
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        read_only: false
        source: ./azbin
        target: /zoo/azbin
      - type: bind
        read_only: true
        source: ./scripts
        target: /zoo/scripts
      - type: bind
        read_only: false
        source: ./conf
        target: /zoo/conf
      - type: bind
        read_only: false
        source: ./dataDirs
        target: /zoo/dataDirs
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /zoo/server.jar

    networks:
      zookeeper-network:
        ipv4_address: 172.200.202.6

    entrypoint: /zoo/scripts/runServer.sh --config /zoo/conf/5 start-foreground




networks:
  zookeeper-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.202.0/24"
          gateway: "172.200.202.1"